const isProd = process.argv.includes("--prod");

module.exports = {
  isProd,
  pug: {
    pretty: !isProd,
    data: {
      head: require("../src/data/head.json"),
    },
  },
  htmlMinifier: {
    includeAutoGeneratedTags: true,
    removeAttributeQuotes: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortClassName: true,
    useShortDoctype: true,
    collapseWhitespace: true,
  },
  typograf: {
    locale: ["ru", "en-US"],
    disableRule: ["ru/other/*"],
  },
  fileInclude: {
    prefix: "@",
    basepath: "@file",
  },
  version: {
    value: "%DT%",
    append: {
      key: "_v",
      cover: 0,
      to: "all",
    },
    output: {
      file: "version.json",
    },
  },
  cleanCss: { level: 2 },
  webpack: {
    mode: isProd ? "production" : "development",
  },
  imagemin: {
    verbose: true,
  },
  webp: {
    quality: isProd ? 70 : null,
  },
  fonter: {
    formats: ["ttf", "woff", "eot", "svg"],
  },
};
